name: Flask Docker CICD Tutorial

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4  
      with: 
        python-versions: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: dummy
      run: ls

    - name: Push image to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest

    - name: Image digest
      run: echo ${{ secrets.build-and-publish.outputs.digest  }}


